// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package it.angelocassano.flutter_nexi.services.payment

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PaymentServicePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class Environment(val raw: Int) {
  TEST(0),
  PRODUCTION(1);

  companion object {
    fun ofRaw(raw: Int): Environment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PaymentResult(val raw: Int) {
  COMPLETED(0),
  CANCELED(1);

  companion object {
    fun ofRaw(raw: Int): PaymentResult? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PaymentRequest (
  val alias: String,
  val codTrans: String,
  val amount: Long,
  val currency: String,
  val secretKey: String,
  val domain: String? = null,
  val environment: Environment
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PaymentRequest {
      val alias = pigeonVar_list[0] as String
      val codTrans = pigeonVar_list[1] as String
      val amount = pigeonVar_list[2] as Long
      val currency = pigeonVar_list[3] as String
      val secretKey = pigeonVar_list[4] as String
      val domain = pigeonVar_list[5] as String?
      val environment = pigeonVar_list[6] as Environment
      return PaymentRequest(alias, codTrans, amount, currency, secretKey, domain, environment)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alias,
      codTrans,
      amount,
      currency,
      secretKey,
      domain,
      environment,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PaymentRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PaymentServicePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PaymentServicePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Environment.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PaymentResult.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Environment -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is PaymentResult -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is PaymentRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PaymentApi {
  fun pay(request: PaymentRequest, callback: (Result<PaymentResult>) -> Unit)

  companion object {
    /** The codec used by PaymentApi. */
    val codec: MessageCodec<Any?> by lazy {
      PaymentServicePigeonCodec()
    }
    /** Sets up an instance of `PaymentApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PaymentApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_nexi.PaymentApi.pay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PaymentRequest
            api.pay(requestArg) { result: Result<PaymentResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PaymentServicePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PaymentServicePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
