import Flutter
import UIKit
import XCTest

@testable import flutter_nexi

// Smoke test for the Swift side of the plugin.
//
// The platform channel is generated by Pigeon (see pigeons/payment_api.dart), so
// there is no method channel handler to exercise here. What is worth guarding is
// the enum wire contract: Pigeon encodes these as ordinals, so reordering a case
// in payment_api.dart would silently swap values across the channel — turning a
// canceled payment into a completed one.
class RunnerTests: XCTestCase {

  func testPaymentServiceImplementsTheGeneratedApi() {
    let api: PaymentApi = PaymentServiceImpl()

    XCTAssertTrue(api is NSObject)
  }

  func testEnumOrdinalsMatchTheDartDefinitions() {
    XCTAssertEqual(Environment.test.rawValue, 0)
    XCTAssertEqual(Environment.production.rawValue, 1)

    XCTAssertEqual(PaymentResult.completed.rawValue, 0)
    XCTAssertEqual(PaymentResult.canceled.rawValue, 1)
  }
}
