name: flutter_nexi
description: "Unofficial Flutter plugin for integrating Nexi/XPay payments on Android and iOS."
version: 1.0.0
repository: https://github.com/AngeloAvv/flutter_nexi
issue_tracker: https://github.com/AngeloAvv/flutter_nexi/issues
homepage: https://www.angelocassano.it

environment:
  sdk: ^3.0.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^25.3.2

flutter:
  plugin:
    platforms:
      android:
        package: it.angelocassano.flutter_nexi
        pluginClass: FlutterNexiPlugin
      ios:
        pluginClass: FlutterNexiPlugin
