// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum PaymentServicePigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum Environment: Int, CaseIterable {
  case test = 0
  case production = 1
}

enum PaymentResult: Int, CaseIterable {
  case completed = 0
  case canceled = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PaymentRequest: Hashable, CustomStringConvertible {
  var alias: String
  var codTrans: String
  var amount: Int64
  var currency: String
  var secretKey: String
  var domain: String? = nil
  var environment: Environment


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PaymentRequest? {
    let alias = pigeonVar_list[0] as! String
    let codTrans = pigeonVar_list[1] as! String
    let amount = pigeonVar_list[2] as! Int64
    let currency = pigeonVar_list[3] as! String
    let secretKey = pigeonVar_list[4] as! String
    let domain: String? = nilOrValue(pigeonVar_list[5])
    let environment = pigeonVar_list[6] as! Environment

    return PaymentRequest(
      alias: alias,
      codTrans: codTrans,
      amount: amount,
      currency: currency,
      secretKey: secretKey,
      domain: domain,
      environment: environment
    )
  }
  func toList() -> [Any?] {
    return [
      alias,
      codTrans,
      amount,
      currency,
      secretKey,
      domain,
      environment,
    ]
  }
  static func == (lhs: PaymentRequest, rhs: PaymentRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PaymentServicePigeonInternal.deepEquals(lhs.alias, rhs.alias) && PaymentServicePigeonInternal.deepEquals(lhs.codTrans, rhs.codTrans) && PaymentServicePigeonInternal.deepEquals(lhs.amount, rhs.amount) && PaymentServicePigeonInternal.deepEquals(lhs.currency, rhs.currency) && PaymentServicePigeonInternal.deepEquals(lhs.secretKey, rhs.secretKey) && PaymentServicePigeonInternal.deepEquals(lhs.domain, rhs.domain) && PaymentServicePigeonInternal.deepEquals(lhs.environment, rhs.environment)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PaymentRequest")
    PaymentServicePigeonInternal.deepHash(value: alias, hasher: &hasher)
    PaymentServicePigeonInternal.deepHash(value: codTrans, hasher: &hasher)
    PaymentServicePigeonInternal.deepHash(value: amount, hasher: &hasher)
    PaymentServicePigeonInternal.deepHash(value: currency, hasher: &hasher)
    PaymentServicePigeonInternal.deepHash(value: secretKey, hasher: &hasher)
    PaymentServicePigeonInternal.deepHash(value: domain, hasher: &hasher)
    PaymentServicePigeonInternal.deepHash(value: environment, hasher: &hasher)
  }

  public var description: String {
    return "PaymentRequest(alias: \(String(describing: alias)), codTrans: \(String(describing: codTrans)), amount: \(String(describing: amount)), currency: \(String(describing: currency)), secretKey: \(String(describing: secretKey)), domain: \(String(describing: domain)), environment: \(String(describing: environment)))"
  }
}

private class PaymentServicePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return Environment(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PaymentResult(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return PaymentRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PaymentServicePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Environment {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PaymentResult {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PaymentRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PaymentServicePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PaymentServicePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PaymentServicePigeonCodecWriter(data: data)
  }
}

class PaymentServicePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PaymentServicePigeonCodec(readerWriter: PaymentServicePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PaymentApi {
  func pay(request: PaymentRequest, completion: @escaping (Result<PaymentResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PaymentApiSetup {
  static var codec: FlutterStandardMessageCodec { PaymentServicePigeonCodec.shared }
  /// Sets up an instance of `PaymentApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PaymentApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let payChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_nexi.PaymentApi.pay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      payChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PaymentRequest
        api.pay(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      payChannel.setMessageHandler(nil)
    }
  }
}
