name: Run Flutter Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Flutter
        uses: ./.github/actions/setup
      - name: Run plugin tests
        run: flutter test
      - name: Run example tests
        working-directory: example
        run: flutter test
